name: Trigger auto deployment for logstreamingdemo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/logstreamingdemo-AutoDeployTrigger-ce31ebc7-8740-477d-8070-5b24d0e368a0.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: xwang971reg.azurecr.io
          username: ${{ secrets.LOGSTREAMINGDEMO_REGISTRY_USERNAME }}
          password: ${{ secrets.LOGSTREAMINGDEMO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xwang971reg.azurecr.io/logstreamingdemo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LOGSTREAMINGDEMO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n logstreamingdemo -g workerapps-rg-xj --server xwang971reg.azurecr.io --username  ${{ secrets.LOGSTREAMINGDEMO_REGISTRY_USERNAME }} --password ${{ secrets.LOGSTREAMINGDEMO_REGISTRY_PASSWORD }}
            az containerapp update -n logstreamingdemo -g workerapps-rg-xj --image xwang971reg.azurecr.io/logstreamingdemo:${{ github.sha }}
