name: Trigger auto deployment for sourcecontrolapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/sourcecontrolapp-AutoDeployTrigger-2ed59fa3-ab87-41d1-b686-bf4cdd437a9c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.SOURCECONTROLAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.SOURCECONTROLAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xwang971/sourcecontrolapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOURCECONTROLAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sourcecontrolapp -g workerapps-rg-xj --server docker.io --username  ${{ secrets.SOURCECONTROLAPP_REGISTRY_USERNAME }} --password ${{ secrets.SOURCECONTROLAPP_REGISTRY_PASSWORD }}
            az containerapp update -n sourcecontrolapp -g workerapps-rg-xj --image xwang971/sourcecontrolapp:${{ github.sha }}
